### ISSUE TITLE
MRTG error

### ISSUE THREAD

**Issue by blageweg** [waelisa/update-script-for-DirectAdmin#2]
--2017-10-04 17:07:04--  https://github.com/waelisa/update-script-for-DirectAdmin/raw/master/core.tgz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-04 17:07:05 ERROR 404: Not Found.

**Comment by waelisa** [comment]
Sorry, so i will upload all the file.

**Comment by waelisa** [comment]
Upload core.tgz done, thanks for report.
